### ISSUE TITLE
Refactor core > graph.h

### ISSUE THREAD

**Issue by Elektra-V** [HBRS-SDP/ss24-physiological-computing#4]
### Description:
The Graph class currently resides in a broader header and is mixed with other functionalities. We aim to refactor this into its own header, graph.h, to isolate its codebase and facilitate easier management and scalability. This move will help in maintaining a clean architecture and improve the separation of concerns within our codebase.

### Tasks:

-  Extract the Graph class definition and relevant components from the current file.
-  Create a new graph.h header to house the Graph class exclusively.
-  Ensure all dependencies and references to the Graph class are updated to point to the new graph.h.
-  Perform thorough testing to confirm that the refactoring has not affected the existing functionality.
-  Update the documentation to reflect the new structure and file changes.

### Expected Outcomes:

- The Graph class functions and interfaces are encapsulated within graph.h.
- Cleaner code structure with better modular separation.
- Easier to maintain and scale the Graph class independently from other components.

Note:
Careful consideration should be given to dependencies and integrations that may be impacted by this change to ensure a smooth transition.

**Comment by Elektra-V** [comment]
This issue has been successfully resolved. We have collected and structured a comprehensive set of dummy data that covers a wide range of environmental conditions and scenarios relevant to our sensor testing needs. The new dataset includes edge cases and extreme values, ensuring robustness in sensor performance across diverse conditions.

**Key Achievements:**

Uniform data formats have been established and implemented across all dummy datasets.
Each data point is now accompanied by accurate timestamps and relevant metadata, enhancing the realism and utility of the dummy data in simulating real-world sensor outputs.

**Comment by ItsShriks** [comment]
Graph.h is independent

**Comment by ItsShriks** [comment]
Testing is pending
